services:
  user_service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_EMBEDDING_UPDATE_TOPIC=${KAFKA_EMBEDDING_UPDATE_TOPIC}
      - KAFKA_BALANCE_INTEREST_TOPIC=${KAFKA_BALANCE_INTEREST_TOPIC}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_TOKEN=${QDRANT_TOKEN}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - OTP_EXPIRY_SECONDS=${OTP_EXPIRY_SECONDS}
      - OTP_REQUEST_LIMIT=${OTP_REQUEST_LIMIT}
      - OTP_RESEND_COOLDOWN=${OTP_RESEND_COOLDOWN}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
  content_service:
    build:
      context: .
      dockerfile: ./content_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - KAFKA_EMBEDDING_UPDATE_TOPIC=${KAFKA_EMBEDDING_UPDATE_TOPIC}
      - KAFKA_BALANCE_INTEREST_TOPIC=${KAFKA_BALANCE_INTEREST_TOPIC}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - CLASSIFIER_MODEL=${CLASSIFIER_MODEL}
      - CLASSIFICATION=${CLASSIFICATION}
      - FETCH_API_URL=${FETCH_API_URL}
      - PROCESS_API_URL=${PROCESS_API_URL}
      - API_KEY=${API_KEY}